Add Dijkstra Implementation, Menu MoreInfos and getSize&Order
JVitorCarv/simple-graphs pull request #4
Opened 2023-11-15 15:45 UTC by EduardoAngelo2803

Implementação do algoritmo de Dijkstra, assim como o menu de More Infos, onde é possível obter a Ordem e tamanho do Grafo com o botão Get Order&Size.

2023-11-15 17:59 UTC, JVitorCarv requested changes
utilizar styled-components

2023-11-15 17:59 UTC, JVitorCarv commented on package-EduardoAngelo.json
Não

2023-11-15 17:59 UTC, JVitorCarv commented on package-lock-EduardoAngelo.json
O que é isso?

2023-11-15 17:59 UTC, JVitorCarv commented on package-lock-EduardoAngelo.json
Wtf

2023-11-15 17:59 UTC, JVitorCarv commented on package-lock.json
Wtf pq deletou o package-lock?

2023-11-15 17:59 UTC, JVitorCarv commented on src/components/GraphEditor/EditorContainer/components/Button/Button.ts
> +      case 'tertiary':
case 'tertiary': é desnecessário porque contem a mesma informação que o default

2023-11-15 17:59 UTC, JVitorCarv commented on src/components/GraphEditor/EditorContainer/components/Button/Button.ts
> +      case 'tertiary':
case 'tertiary': é desnecessário porque contem a mesma informação que o default

2023-11-15 17:59 UTC, JVitorCarv commented on src/components/GraphEditor/Editors/AlgorithmsEditor/AlgorithmsEditor.tsx
> +
deletar essa linha em branco

2023-11-15 17:59 UTC, JVitorCarv commented on src/components/GraphEditor/Editors/AlgorithmsEditor/components/DijkstraAlgorithm/DijkstraAlgorithm.tsx
> +
ilegível. Transferir todos os inline styles para um styled.ts

2023-11-15 17:59 UTC, JVitorCarv commented on src/components/GraphEditor/Editors/AlgorithmsEditor/components/DijkstraAlgorithm/DijkstraAlgorithm.tsx
> +  const resetAlgorithm = () => {
resetAlgorithm faz a mesma coisa que o clearSelection. Remover

2023-11-15 17:59 UTC, JVitorCarv commented on src/components/GraphEditor/Editors/AlgorithmsEditor/components/DijkstraAlgorithm/DijkstraAlgorithm.tsx
> +        setErrorMessage('Sem caminhos disponíveis. Não é possível executar o algoritmo para os nós selecionados.');
Mensagem em português

2023-11-15 17:59 UTC, JVitorCarv commented on src/components/GraphEditor/Editors/AlgorithmsEditor/components/DijkstraAlgorithm/DijkstraAlgorithm.tsx
> +      {errorMessage && (
Mais uma vez inline-styling ilegível.

2023-11-15 17:59 UTC, JVitorCarv commented on src/components/GraphEditor/Editors/AlgorithmsEditor/components/DijkstraAlgorithm/DijkstraAlgorithm.tsx
> +        <ErrorMessage message={`Sem caminhos disponíveis. Não é possível executar o algoritmo do nó ${cy.current.$(`#${sourceNode}`).data('label')} para o nó ${cy.current.$(`#${targetNode}`).data('la
Mensagem em português

2023-11-15 17:59 UTC, JVitorCarv commented on src/components/GraphEditor/Editors/AlgorithmsEditor/components/DijkstraAlgorithm/DijkstraAlgorithm.tsx
> +        <ErrorMessage message={`Sem caminhos disponíveis. Não é possível executar o algoritmo do nó ${cy.current.$(`#${sourceNode}`).data('label')} para o nó ${cy.current.$(`#${targetNode}`).data('la
Por que tem duas mensagens de erro diferentes dizendo a mesma coisa?

2023-11-15 17:59 UTC, JVitorCarv commented on src/components/GraphEditor/Editors/MoreInfosEditor/MoreInfosEditor.tsx
> +            {mode === '' && <InstructionBox content={"Select a Mode"} />}
indentação errada

2023-11-15 17:59 UTC, JVitorCarv commented on src/components/GraphEditor/Editors/MoreInfosEditor/MoreInfosEditor.tsx
> +
linha em branco

2023-11-15 17:59 UTC, JVitorCarv commented on src/components/GraphEditor/Editors/MoreInfosEditor/SizeOrderEditor/SizeOrderEditor.tsx
> +
linha em branco

2023-11-15 17:59 UTC, JVitorCarv commented on src/components/GraphEditor/Editors/MoreInfosEditor/SizeOrderEditor/SizeOrderEditor.tsx
> +  // Calcule o tamanho do grafo
comentário do gpt

2023-11-15 17:59 UTC, JVitorCarv commented on src/components/GraphEditor/Editors/MoreInfosEditor/SizeOrderEditor/SizeOrderEditor.tsx
> +          <h2 style={{ margin: '0', color: 'var(--colors-blue, #007AFF)', lineHeight: '1.5' }}>{size}</h2>
de novo, inline-styling

2023-11-17 22:01 UTC, JVitorCarv requested changes

2023-11-17 22:01 UTC, vitorvelozo commented on .gitignore
Isso não pode ser feito

2023-11-17 22:02 UTC, MatheusBarros23 commented on .gitignore
Isso aqui precisa estar no diretorio, só assim conseguimos fazer o build, dev e, depois, deploy.
E da pra tirar o dist tbm!

2023-11-17 22:03 UTC, EduardoAngelo2803 commented on .gitignore
os dois?
dist
dist-ssr

2023-11-17 22:04 UTC, closed without merging

2023-11-17 22:05 UTC, MatheusBarros23 commented on .gitignore
Deixar o dist e os 2 packages fora do .gitignore. Pq assim a gente vai ter as dependencias do que tu fez